# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/devops/ci.yml
      - sdk/devops/azure-resourcemanager-devops/
    exclude:
      - sdk/devops/pom.xml
      - sdk/devops/azure-resourcemanager-devops/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/devops/ci.yml
      - sdk/devops/azure-resourcemanager-devops/
    exclude:
      - sdk/devops/pom.xml
      - sdk/devops/azure-resourcemanager-devops/pom.xml

parameters:
  - name: release_azureresourcemanagerdevops
    displayName: azure-resourcemanager-devops
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: devops
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-devops
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdevops
        releaseInBatch: ${{ parameters.release_azureresourcemanagerdevops }}
